<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CpuEmulator.Core\CpuEmulator.Core.csproj" />
    <ProjectReference Include="..\..\src\CpuEmulator.Peripherals\CpuEmulator.Peripherals.csproj" />
    <ProjectReference Include="..\..\src\CpuEmulator.Machines\CpuEmulator.Machines.csproj" />
  </ItemGroup>
</Project>
