using System.Text;

namespace CpuEmulator.SpecImporter;

/// <summary>A report from the FieldGrammar emitter (the arm's analog of ImportReport).</summary>
public sealed record FieldGrammarReport(int Families)
{
    public override string ToString() => $"families={Families}";
}

/// <summary>
/// Emits a complete spec-class source file from a FieldGrammar dataset + config. The spec declares the
/// 68000 state model (Registers + FlagLayout) AND a populated FieldGrammar (Decode68k) the M4.3a generator
/// expands into the Decode(IFetchStream) field-decode walk. Instructions is EMPTY — the op BODIES are M4.5.
/// Family order in the dataset is preserved (the (opIndex, size) key identity — F2).
/// </summary>
public static class FieldGrammarEmitter
{
    public static (string Source, FieldGrammarReport Report) Emit(
        FieldGrammarFamily[] families,
        FieldGrammarConfig   config,
        string               datasetPath = "data/m68000-fieldgrammar.json",
        string               outputPath  = "src/CpuEmulator.Cpus.M68000/M68000Spec.cs")
    {
        var sb = new StringBuilder();

        // ── header ──
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Tool    : CpuEmulator.SpecImporter (FieldGrammar arm)");
        sb.AppendLine($"//   Dataset : {datasetPath}");
        sb.AppendLine($"//   Families: {families.Length}");
        sb.AppendLine("//   Regenerate :");
        sb.AppendLine("//     dotnet run --project tools/CpuEmulator.SpecImporter -- \\");
        sb.AppendLine($"//       --field-grammar {datasetPath} \\");
        sb.AppendLine($"//       --config tools/CpuEmulator.SpecImporter/data/m68000-fieldgrammar-config.json \\");
        sb.AppendLine($"//       --out {outputPath}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("using CpuEmulator.Core.Specification;");
        sb.AppendLine("using static CpuEmulator.Core.Specification.Spec;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"[CpuSpecification(\"{config.Architecture}\")]");
        sb.AppendLine($"public static class {config.SpecClassName}");
        sb.AppendLine("{");

        // ── Registers (same emit shape as SpecFileEmitter — byte-identical to the M4.1 hand-write, D2) ──
        sb.AppendLine("    public static readonly RegisterDef[] Registers =");
        sb.AppendLine("    [");
        foreach (var reg in config.Registers)
        {
            string rolePart = reg.Role switch
            {
                "StackPointer"   => ", RegisterRole.StackPointer",
                "Status"         => ", RegisterRole.Status",
                "ProgramCounter" => ", RegisterRole.ProgramCounter",
                _                => "",
            };
            sb.AppendLine($"        new(\"{reg.Name}\", {reg.Bits}{rolePart}),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();

        // ── FlagLayout ──
        if (config.Flags.Length > 0)
        {
            string bits = string.Join(", ", config.Flags.Select(b => $"new(\"{b.Name}\", {b.Bit})"));
            sb.AppendLine($"    public static readonly FlagLayout Flags = new([{bits}]);");
            sb.AppendLine();
        }

        // ── the FieldGrammar (Decode68k) — the M4.4a payload ──
        sb.AppendLine("    public static readonly FieldGrammar Decode68k = new(");
        sb.AppendLine("        FetchUnit.Word,");
        sb.AppendLine("        [");
        foreach (var f in families)
            sb.AppendLine(
                $"            FieldOp(Mask: 0x{f.Mask:X4}, Match: 0x{f.Match:X4}, Operation: \"{f.Operation}\", " +
                $"SizeShift: {f.SizeShift}, SizeWidth: {f.SizeWidth}, SizeEncoding: SizeEncoding.{f.SizeEncoding}, " +
                $"EaShift: {f.EaShift}, LegalEa: EaCategory.{f.LegalEa}),");
        sb.AppendLine("        ]);");
        sb.AppendLine();

        // ── Instructions: EMPTY (op bodies are M4.5) ──
        sb.AppendLine("    public static readonly InstructionDef[] Instructions = [];");
        sb.AppendLine("}");

        return (sb.ToString(), new FieldGrammarReport(families.Length));
    }
}
