using System.Text;

namespace CpuEmulator.SpecImporter;

/// <summary>
/// A report returned by the emitter summarising what was emitted versus deferred.
/// </summary>
public sealed record ImportReport(
    int Total,
    int Emitted,
    int TodoSemantics,
    int TodoMode)
{
    /// <summary>
    /// Per-mnemonic inventory of dataset rows lacking semantics
    /// (mnemonic → dataset-row count), ordered by mnemonic for stable output.
    /// Printed by the CLI under <c>--report</c>.
    /// </summary>
    public IReadOnlyList<(string Mnemonic, int Rows)> MissingSemanticsInventory { get; init; } = [];

    /// <summary>Returns the single-line summary written to stdout by the CLI.</summary>
    public override string ToString() =>
        $"total={Total} emitted={Emitted} todoSemantics={TodoSemantics} todoMode={TodoMode}";
}

/// <summary>
/// Emits a complete spec-class source file from a loaded dataset + semantics map.
///
/// Emission rules (dataset opcode order throughout — diffs against regenerations are stable):
///   mnemonic in map AND mode in DSL's 5 → real Insn(...) row
///   mnemonic in map, mode NOT supported  → // TODO(mode): ...
///   mnemonic NOT in map                  → // TODO(semantics): ...
///
/// The 5 DSL-supported modes mirror AddrMode in CpuEmulator.Core.Specification.
/// SYNC HAZARD: if AddrMode gains new members this set must expand in concert.
/// </summary>
public static class SpecFileEmitter
{
    // The 5 modes currently expressible by the DSL (mirrors AddrMode enum).
    private static readonly HashSet<string> SupportedModes =
        ["Implied", "Immediate", "ZeroPage", "Absolute", "Relative"];

    /// <summary>
    /// Emits the spec source and returns (source, report).
    /// </summary>
    public static (string Source, ImportReport Report) Emit(
        OpcodeEntry[]  dataset,
        SemanticsMap   map,
        string         datasetPath   = "mos6502-opcodes.json",
        string         semanticsPath = "mos6502-semantics.json")
    {
        var sb = new StringBuilder();
        int emitted       = 0;
        int todoSemantics = 0;
        int todoMode      = 0;
        // mnemonic → count of dataset rows lacking semantics (sorted for stable report output)
        var missingSemantics = new SortedDictionary<string, int>(StringComparer.Ordinal);

        // ── auto-generated header ────────────────────────────────────────────
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Tool    : CpuEmulator.SpecImporter");
        sb.AppendLine($"//   Dataset : {datasetPath}");
        sb.AppendLine($"//   Semantics: {semanticsPath}");
        sb.AppendLine($"//   Total rows : {dataset.Length}");
        sb.AppendLine("//   Regenerate : dotnet run --project tools/CpuEmulator.SpecImporter -- \\");
        sb.AppendLine($"//                 --dataset {datasetPath} --semantics {semanticsPath} --out <output>");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // ── usings ───────────────────────────────────────────────────────────
        sb.AppendLine("using CpuEmulator.Core.Specification;");
        sb.AppendLine("using static CpuEmulator.Core.Specification.Spec;");
        sb.AppendLine();

        // ── namespace + class declaration ────────────────────────────────────
        sb.AppendLine($"namespace {map.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"[CpuSpecification(\"{map.Architecture}\")]");
        sb.AppendLine($"public static class {map.SpecClassName}");
        sb.AppendLine("{");

        // ── Registers table ───────────────────────────────────────────────────
        sb.AppendLine("    public static readonly RegisterDef[] Registers =");
        sb.AppendLine("    [");
        foreach (var reg in map.Registers)
        {
            var rolePart = reg.Role switch
            {
                "StackPointer"   => ", RegisterRole.StackPointer",
                "Status"         => ", RegisterRole.Status",
                "ProgramCounter" => ", RegisterRole.ProgramCounter",
                _                => ""
            };
            sb.AppendLine($"        new(\"{reg.Name}\", {reg.Bits}{rolePart}),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();

        // ── Instructions collection ───────────────────────────────────────────
        sb.AppendLine("    public static readonly InstructionDef[] Instructions =");
        sb.AppendLine("    [");

        foreach (var entry in dataset)
        {
            bool hasSemantics = map.Mnemonics.TryGetValue(entry.Mnemonic, out var opsText);
            bool modeSupported = SupportedModes.Contains(entry.Mode);

            if (hasSemantics && modeSupported)
            {
                // Real row — emit Insn(...)
                sb.AppendLine(
                    $"        Insn({entry.Opcode}, \"{entry.Mnemonic}\", AddrMode.{entry.Mode}, {opsText}),");
                emitted++;
            }
            else if (hasSemantics)
            {
                // Semantics known but mode not yet supported by DSL
                sb.AppendLine(
                    $"        // TODO(mode): {entry.Opcode} {entry.Mnemonic} {entry.Mode} — awaiting AddrMode support");
                todoMode++;
            }
            else
            {
                // No semantics yet
                sb.AppendLine(
                    $"        // TODO(semantics): {entry.Opcode} {entry.Mnemonic} {entry.Mode} — awaiting micro-op vocabulary");
                todoSemantics++;
                missingSemantics[entry.Mnemonic] = missingSemantics.GetValueOrDefault(entry.Mnemonic) + 1;
            }
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");

        var report = new ImportReport(dataset.Length, emitted, todoSemantics, todoMode)
        {
            MissingSemanticsInventory = [.. missingSemantics.Select(kv => (kv.Key, kv.Value))],
        };
        return (sb.ToString(), report);
    }
}
