using System.Text;

namespace CpuEmulator.SpecImporter;

/// <summary>A report from the x86 emitter (the arm's analog of <see cref="ImportReport"/>/
/// <see cref="FieldGrammarReport"/>).</summary>
public sealed record X86Report(int Prefixes, int Opcodes, int Instructions)
{
    public override string ToString() =>
        $"prefixes={Prefixes} opcodes={Opcodes} instructions={Instructions}";
}

/// <summary>
/// Emits a complete spec-class source file from an x86 dataset + config (M5.4). The spec declares the 8086
/// state model (Registers + FlagLayout) AND a populated <c>X86DecodeStructure</c> (the prefix set + the
/// per-opcode decode metadata) the generator's <c>EmitX86DecodeWalk</c> arm expands into the variable-length
/// decode walk, PLUS the Instructions table — one Insn row per dataset row, with an EMPTY Op[] (the op BODIES
/// are M5.5). Each plain opcode is declared once in the X86DecodeStructure and backs >=1 non-group Insn row;
/// each group opcode is declared once and backs >=1 OpcodeGroup Insn row (the generator's CPUGEN016
/// cross-check). Dataset order is preserved (the regen byte-identity guard pins it).
/// </summary>
public static class X86Emitter
{
    public static (string Source, X86Report Report) Emit(
        X86Dataset dataset,
        X86Config  config,
        string     datasetPath = "tools/CpuEmulator.SpecImporter/data/m8086-opcodes.json",
        string     configPath  = "tools/CpuEmulator.SpecImporter/data/m8086-x86-config.json",
        string     outputPath  = "src/CpuEmulator.Cpus.M8086/M8086Spec.cs")
    {
        var sb = new StringBuilder();

        // ── header ──
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Tool    : CpuEmulator.SpecImporter (x86 arm)");
        sb.AppendLine($"//   Dataset : {datasetPath}");
        sb.AppendLine($"//   Prefixes: {dataset.Prefixes.Length}");
        sb.AppendLine($"//   Opcodes : {CountUniqueOpcodes(dataset)}");
        sb.AppendLine($"//   Insns   : {dataset.Opcodes.Length}");
        sb.AppendLine("//   Regenerate :");
        sb.AppendLine("//     dotnet run --project tools/CpuEmulator.SpecImporter -- \\");
        sb.AppendLine($"//       --x86 {datasetPath} \\");
        sb.AppendLine($"//       --config {configPath} \\");
        sb.AppendLine($"//       --out {outputPath}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        sb.AppendLine("using CpuEmulator.Core.Specification;");
        sb.AppendLine("using static CpuEmulator.Core.Specification.Spec;");
        sb.AppendLine();
        sb.AppendLine($"namespace {config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"[CpuSpecification(\"{config.Architecture}\")]");
        sb.AppendLine($"public static class {config.SpecClassName}");
        sb.AppendLine("{");

        // ── Registers (same emit shape as SpecFileEmitter — the pair-view HighHalf/LowHalf included) ──
        sb.AppendLine("    public static readonly RegisterDef[] Registers =");
        sb.AppendLine("    [");
        foreach (var reg in config.Registers)
        {
            string rolePart = reg.Role switch
            {
                "StackPointer"   => ", RegisterRole.StackPointer",
                "Status"         => ", RegisterRole.Status",
                "ProgramCounter" => ", RegisterRole.ProgramCounter",
                _                => "",
            };
            string pairPart = reg.HighHalf is not null && reg.LowHalf is not null
                ? $", HighHalf: \"{reg.HighHalf}\", LowHalf: \"{reg.LowHalf}\""
                : "";
            sb.AppendLine($"        new(\"{reg.Name}\", {reg.Bits}{rolePart}{pairPart}),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine();

        // ── FlagLayout ──
        if (config.Flags.Length > 0)
        {
            string bits = string.Join(", ", config.Flags.Select(b => $"new(\"{b.Name}\", {b.Bit})"));
            sb.AppendLine($"    public static readonly FlagLayout Flags = new([{bits}]);");
            sb.AppendLine();
        }

        // ── the X86DecodeStructure (the M5.4 payload the EmitX86DecodeWalk arm expands) ──
        sb.AppendLine("    public static readonly X86DecodeStructure Decode = new(");
        sb.AppendLine("        Prefixes:");
        sb.AppendLine("        [");
        foreach (var p in dataset.Prefixes)
            sb.AppendLine($"            new X86Prefix(0x{p.Value:X2}, X86PrefixRole.{p.Role}),");
        sb.AppendLine("        ],");
        sb.AppendLine("        Opcodes:");
        sb.AppendLine("        [");
        // One X86Opcode per UNIQUE primary opcode, in first-appearance order (a group's members share one
        // declaration). Only the non-default fields are written (matching the carrier's defaults) so the
        // emitted creation is minimal + readable.
        foreach (byte op in UniqueOpcodesInOrder(dataset))
        {
            var meta = MetaFor(dataset, op);
            sb.AppendLine($"            {EmitX86Opcode(op, meta)},");
        }
        sb.AppendLine("        ]);");
        sb.AppendLine();

        // ── Instructions: one row per dataset row, op BODIES empty (M5.5). The disassembly mnemonic is
        //    carried; AddrMode.Implied + [] keep the row a pure decode-table anchor until the bodies land. ──
        sb.AppendLine("    public static readonly InstructionDef[] Instructions =");
        sb.AppendLine("    [");
        foreach (var row in dataset.Opcodes)
        {
            if (row.RegIsExtension)
                sb.AppendLine(
                    $"        Insn(0x{row.Opcode:X2}, subfield: {row.Subfield}, \"{row.Mnemonic}\", AddrMode.Implied, []),");
            else
                sb.AppendLine(
                    $"        Insn(0x{row.Opcode:X2}, \"{row.Mnemonic}\", AddrMode.Implied, []),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine("}");

        var report = new X86Report(dataset.Prefixes.Length, CountUniqueOpcodes(dataset), dataset.Opcodes.Length);
        return (sb.ToString(), report);
    }

    /// <summary>Render one <c>X86Opcode(...)</c> creation, writing only the non-default fields (the carrier
    /// defaults are HasModRm:false, RegIsExtension:false, WBit:-1, SBit:-1, Immediate:None).</summary>
    private static string EmitX86Opcode(
        byte opcode, (bool HasModRm, bool RegIsExtension, int WBit, int SBit, X86ImmediateKind Imm) m)
    {
        var args = new List<string> { $"0x{opcode:X2}" };
        if (m.HasModRm) args.Add("HasModRm: true");
        if (m.RegIsExtension) args.Add("RegIsExtension: true");
        if (m.WBit != -1) args.Add($"WBit: {m.WBit}");
        if (m.SBit != -1) args.Add($"SBit: {m.SBit}");
        if (m.Imm != X86ImmediateKind.None) args.Add($"Immediate: X86ImmediateRule.{m.Imm}");
        return $"new X86Opcode({string.Join(", ", args)})";
    }

    private static IEnumerable<byte> UniqueOpcodesInOrder(X86Dataset dataset)
    {
        var seen = new HashSet<byte>();
        foreach (var row in dataset.Opcodes)
            if (seen.Add(row.Opcode))
                yield return row.Opcode;
    }

    private static int CountUniqueOpcodes(X86Dataset dataset) =>
        UniqueOpcodesInOrder(dataset).Count();

    private static (bool, bool, int, int, X86ImmediateKind) MetaFor(X86Dataset dataset, byte opcode)
    {
        // All rows for one opcode carry identical metadata (X86Dataset.Parse enforces this); take the first.
        var row = dataset.Opcodes.First(r => r.Opcode == opcode);
        return (row.HasModRm, row.RegIsExtension, row.WBit, row.SBit, row.Immediate);
    }
}
