using CpuEmulator.Core.Jit;
using CpuEmulator.Cpus.Mos6502;

namespace CpuEmulator.Tests.Jit;

/// <summary>Task 1: pins the generated <c>Mos6502Cpu.JitDescriptors</c> table (artifact ③ in
/// data form) against the interpreter's own truth — instruction length, base cycles, the
/// page-cross predicate, the ambition-decision fallback set, block-ending classification, and
/// per-class op fidelity. The table is generated by reusing the SAME ModeLength/ComputeCycles
/// functions the interpreter body emission uses, so these tests guard against drift.</summary>
public class OpcodeDescriptorTests
{
    private static bool IsDocumented(byte opcode) =>
        Mos6502Cpu.Disassemble(opcode, 0, 0) != "???";

    [Fact]
    public void JitDescriptors_has_256_entries_indexable_by_opcode()
    {
        Assert.Equal(256, Mos6502Cpu.JitDescriptors.Length);

        for (int op = 0; op <= 0xFF; op++)
        {
            OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[op];
            Assert.Equal((byte)op, d.Opcode);
            if (!IsDocumented((byte)op))
            {
                Assert.Equal(JitOpClass.Undefined, d.Class);
                Assert.True(d.NeedsFallback, $"undefined opcode 0x{op:X2} must need fallback");
                Assert.True(d.EndsBlock, $"undefined opcode 0x{op:X2} must end the block");
            }
        }
    }

    [Fact]
    public void JitDescriptors_covers_all_151_documented_opcodes()
    {
        int documented = 0;
        for (int op = 0; op <= 0xFF; op++)
        {
            OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[op];
            if (d.Class == JitOpClass.Undefined)
                continue;
            documented++;
            string disasm = Mos6502Cpu.Disassemble((byte)op, 0, 0);
            Assert.NotEqual("???", disasm);
            // The mnemonic is the first whitespace-delimited token of the disassembly.
            string mnemonic = disasm.Split(' ')[0];
            Assert.Equal(mnemonic, d.Mnemonic);
            Assert.Equal(Mos6502Cpu.InstructionLength((byte)op), d.Length);
        }

        Assert.Equal(151, documented);
    }

    public static TheoryData<byte, int> CycleTemplate() => new()
    {
        { 0xA5, 3 },  // LDA ZeroPage
        { 0xAD, 4 },  // LDA Absolute
        { 0x8D, 4 },  // STA Absolute
        { 0x4C, 3 },  // JMP Absolute
        { 0x20, 6 },  // JSR Absolute
        { 0x60, 6 },  // RTS Implied
        { 0x48, 3 },  // PHA Implied (push = 3)
        { 0x68, 4 },  // PLA Implied (pull = 4)
        { 0x06, 5 },  // ASL ZeroPage (RMW)
        { 0xFE, 7 },  // INC AbsoluteX (RMW, always 7)
    };

    [Theory]
    [MemberData(nameof(CycleTemplate))]
    public void JitDescriptor_BaseCycles_matches_the_interpreter_cycle_template(byte opcode, int expected)
    {
        Assert.Equal(expected, Mos6502Cpu.JitDescriptors[opcode].BaseCycles);
    }

    [Theory]
    [InlineData(0xBD)]  // LDA AbsoluteX (Load) — page-cross +1
    [InlineData(0xB9)]  // LDA AbsoluteY (Load) — page-cross +1
    [InlineData(0xB1)]  // LDA IndirectY (Load) — page-cross +1
    [InlineData(0x7D)]  // ADC AbsoluteX (Alu) — page-cross +1
    [InlineData(0x79)]  // ADC AbsoluteY (Alu) — page-cross +1
    [InlineData(0x71)]  // ADC IndirectY (Alu) — page-cross +1
    public void JitDescriptor_PageCrossPenalty_set_on_indexed_load_alu(byte opcode)
    {
        Assert.True(Mos6502Cpu.JitDescriptors[opcode].PageCrossPenalty,
            $"opcode 0x{opcode:X2} (indexed Load/Alu) must carry the page-cross penalty");
    }

    [Theory]
    [InlineData(0x9D)]  // STA AbsoluteX — store is always 5, no penalty
    [InlineData(0x99)]  // STA AbsoluteY — store is always 5, no penalty
    [InlineData(0xA5)]  // LDA ZeroPage — not indexed
    [InlineData(0xAD)]  // LDA Absolute — not indexed
    [InlineData(0xA9)]  // LDA Immediate — no memory address
    [InlineData(0xEA)]  // NOP Implied
    public void JitDescriptor_PageCrossPenalty_clear_on_non_indexed_load_alu(byte opcode)
    {
        Assert.False(Mos6502Cpu.JitDescriptors[opcode].PageCrossPenalty,
            $"opcode 0x{opcode:X2} must NOT carry the page-cross penalty");
    }

    // BRK + RTI remain interpreter fallbacks (M2-ii recorded decision: they touch the
    // interrupt/vector machinery the interpreter owns; emitting them buys ~0 throughput and risks
    // the highest-cost parity hole). ADC/SBC are NO LONGER here — Task 5 emits them (below).
    public static TheoryData<byte> BrkRtiOpcodes() => new()
    {
        0x00, 0x40,   // BRK, RTI
    };

    [Theory]
    [MemberData(nameof(BrkRtiOpcodes))]
    public void JitDescriptor_NeedsFallback_exactly_on_BRK_RTI_and_undefined(byte opcode)
    {
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[opcode];
        Assert.True(d.NeedsFallback, $"opcode 0x{opcode:X2} must carry NeedsFallback");
        Assert.True(d.EndsBlock, $"opcode 0x{opcode:X2} fallback must end the block");
    }

    public static TheoryData<byte> AdcSbcOpcodes() => new()
    {
        // ADC, all 8 modes
        0x69, 0x65, 0x75, 0x6D, 0x7D, 0x79, 0x61, 0x71,
        // SBC, all 8 modes
        0xE9, 0xE5, 0xF5, 0xED, 0xFD, 0xF9, 0xE1, 0xF1,
    };

    [Theory]
    [MemberData(nameof(AdcSbcOpcodes))]
    public void JitDescriptor_ADC_SBC_are_now_emitted_not_fallback(byte opcode)
    {
        // Task 5 (the M2-i ambition decision's planned M2-ii flip): ADC/SBC are emitted in both the
        // binary and decimal arms, so they are straight-line Alu-class — NeedsFallback false AND
        // EndsBlock false (an ADC/SBC no longer ends a block).
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[opcode];
        Assert.Equal(JitOpClass.Alu, d.Class);
        Assert.False(d.NeedsFallback, $"opcode 0x{opcode:X2} (ADC/SBC) is now emitted — no fallback");
        Assert.False(d.EndsBlock, $"opcode 0x{opcode:X2} (ADC/SBC) is straight-line — must not end a block");
    }

    [Theory]
    [InlineData(0xA9)]  // LDA Immediate
    [InlineData(0x8D)]  // STA Absolute
    [InlineData(0x29)]  // AND Immediate
    [InlineData(0x09)]  // ORA Immediate
    [InlineData(0x49)]  // EOR Immediate
    [InlineData(0xC9)]  // CMP Immediate
    [InlineData(0x06)]  // ASL ZeroPage
    [InlineData(0xAA)]  // TAX Implied
    public void JitDescriptor_NeedsFallback_clear_on_emittable_opcodes(byte opcode)
    {
        Assert.False(Mos6502Cpu.JitDescriptors[opcode].NeedsFallback,
            $"opcode 0x{opcode:X2} must be emittable (no fallback)");
    }

    [Theory]
    [InlineData(0xD0, JitOpClass.Branch)]  // BNE Relative
    [InlineData(0x4C, JitOpClass.Jump)]    // JMP Absolute
    [InlineData(0x6C, JitOpClass.Jump)]    // JMP Indirect
    [InlineData(0x20, JitOpClass.Jsr)]     // JSR Absolute
    [InlineData(0x60, JitOpClass.Rts)]     // RTS Implied
    [InlineData(0x00, JitOpClass.Flow)]    // BRK Implied
    [InlineData(0x40, JitOpClass.Flow)]    // RTI Implied
    public void JitDescriptor_EndsBlock_on_control_flow(byte opcode, JitOpClass expectedClass)
    {
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[opcode];
        Assert.Equal(expectedClass, d.Class);
        Assert.True(d.EndsBlock, $"opcode 0x{opcode:X2} ({expectedClass}) must end a block");
    }

    [Theory]
    [InlineData(0xA9)]  // LDA Immediate (Load)
    [InlineData(0x8D)]  // STA Absolute (Store)
    [InlineData(0xAA)]  // TAX Implied (Register)
    [InlineData(0x06)]  // ASL ZeroPage (Rmw)
    [InlineData(0x29)]  // AND Immediate (Alu, non-fallback)
    public void JitDescriptor_does_not_end_block_on_straight_line_ops(byte opcode)
    {
        Assert.False(Mos6502Cpu.JitDescriptors[opcode].EndsBlock,
            $"opcode 0x{opcode:X2} is straight-line and must not end a block");
    }

    [Fact]
    public void JitDescriptor_LDA_carries_load_and_setnz_ops()
    {
        // LDA Immediate (0xA9): Load("A") + SetNZ("A"). RegA carries the register NAME (J2).
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[0xA9];
        Assert.Equal(JitOpClass.Load, d.Class);
        Assert.Equal(2, d.Ops.Length);
        Assert.Equal("Load", d.Ops[0].Kind);
        Assert.Equal("A", d.Ops[0].RegA);
        Assert.Equal("", d.Ops[0].RegB);       // no second register operand
        Assert.Equal("SetNZ", d.Ops[1].Kind);
        Assert.Equal("A", d.Ops[1].RegA);
    }

    [Fact]
    public void JitOp_register_slots_carry_names_not_indices()
    {
        // TAX Implied (0xAA): Transfer("A","X") + SetNZ("X"). The descriptor row carries register
        // NAMES, not byte indices (the retired RegIndex would have emitted 0/1) — the J2 win.
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[0xAA];
        Assert.Equal(JitOpClass.Register, d.Class);
        Assert.Equal("Transfer", d.Ops[0].Kind);
        Assert.Equal("A", d.Ops[0].RegA);
        Assert.Equal("X", d.Ops[0].RegB);
        Assert.Equal("SetNZ", d.Ops[1].Kind);
        Assert.Equal("X", d.Ops[1].RegA);
    }

    [Fact]
    public void JitOp_zero_arg_op_carries_empty_register_slots()
    {
        // JMP Absolute (0x4C): Jump() carries no register operands — both slots are "".
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[0x4C];
        JitOp op = Assert.Single(d.Ops);
        Assert.Equal("Jump", op.Kind);
        Assert.Equal("", op.RegA);
        Assert.Equal("", op.RegB);
    }

    [Fact]
    public void JitDescriptor_BNE_carries_branchif_Z_false()
    {
        // BNE (0xD0): BranchIf(Z, when:false). Z bit == 1.
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[0xD0];
        JitOp op = Assert.Single(d.Ops);
        Assert.Equal("BranchIf", op.Kind);
        Assert.Equal(1, op.FlagBit);       // Z
        Assert.False(op.BoolArg);          // when == false
    }

    [Fact]
    public void JitDescriptor_CLC_carries_setflag_C_false()
    {
        // CLC (0x18): SetFlag(C, value:false). C bit == 0.
        OpcodeDescriptor d = Mos6502Cpu.JitDescriptors[0x18];
        JitOp op = Assert.Single(d.Ops);
        Assert.Equal("SetFlag", op.Kind);
        Assert.Equal(0, op.FlagBit);       // C
        Assert.False(op.BoolArg);          // value == false
    }
}
