// <auto-generated>
//   Tool    : CpuEmulator.SpecImporter (FieldGrammar arm)
//   Dataset : tools/CpuEmulator.SpecImporter/data/m68000-fieldgrammar.json
//   Families: 83
//   Regenerate :
//     dotnet run --project tools/CpuEmulator.SpecImporter -- \
//       --field-grammar tools/CpuEmulator.SpecImporter/data/m68000-fieldgrammar.json \
//       --config tools/CpuEmulator.SpecImporter/data/m68000-fieldgrammar-config.json \
//       --out src/CpuEmulator.Cpus.M68000/M68000Spec.cs
// </auto-generated>

using CpuEmulator.Core.Specification;
using static CpuEmulator.Core.Specification.Spec;

namespace CpuEmulator.Cpus.M68000;

[CpuSpecification("m68000")]
public static class M68000Spec
{
    public static readonly RegisterDef[] Registers =
    [
        new("D0", 32),
        new("D1", 32),
        new("D2", 32),
        new("D3", 32),
        new("D4", 32),
        new("D5", 32),
        new("D6", 32),
        new("D7", 32),
        new("A0", 32),
        new("A1", 32),
        new("A2", 32),
        new("A3", 32),
        new("A4", 32),
        new("A5", 32),
        new("A6", 32),
        new("USP", 32),
        new("SSP", 32, RegisterRole.StackPointer),
        new("PC", 32, RegisterRole.ProgramCounter),
        new("SR", 16, RegisterRole.Status),
    ];

    public static readonly FlagLayout Flags = new([new("C", 0), new("V", 1), new("Z", 2), new("N", 3), new("X", 4), new("S", 13)]);

    public static readonly FieldGrammar Decode68k = new(
        FetchUnit.Word,
        [
            FieldOp(Mask: 0xFFFF, Match: 0x003C, Operation: "ORI_CCR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x007C, Operation: "ORI_SR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x023C, Operation: "ANDI_CCR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x027C, Operation: "ANDI_SR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x0A3C, Operation: "EORI_CCR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x0A7C, Operation: "EORI_SR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF038, Match: 0x0008, Operation: "MOVEP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFC0, Match: 0x0800, Operation: "BTST_STATIC", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xFFC0, Match: 0x0840, Operation: "BCHG_STATIC", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFFC0, Match: 0x0880, Operation: "BCLR_STATIC", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFFC0, Match: 0x08C0, Operation: "BSET_STATIC", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xF1C0, Match: 0x0100, Operation: "BTST", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1C0, Match: 0x0140, Operation: "BCHG", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xF1C0, Match: 0x0180, Operation: "BCLR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xF1C0, Match: 0x01C0, Operation: "BSET", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x0600, Operation: "ADDI", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x0400, Operation: "SUBI", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x0200, Operation: "ANDI", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x0000, Operation: "ORI", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x0A00, Operation: "EORI", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x0C00, Operation: "CMPI", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xC1C0, Match: 0x0040, Operation: "MOVEA", SizeShift: 12, SizeWidth: 2, SizeEncoding: SizeEncoding.Move, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xC000, Match: 0x0000, Operation: "MOVE", SizeShift: 12, SizeWidth: 2, SizeEncoding: SizeEncoding.Move, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E76, Operation: "TRAPV", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E73, Operation: "RTE", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E75, Operation: "RTS", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E77, Operation: "RTR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E70, Operation: "RESET", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E71, Operation: "NOP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4E72, Operation: "STOP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFFF, Match: 0x4AFC, Operation: "ILLEGAL", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFF8, Match: 0x4840, Operation: "SWAP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFF8, Match: 0x4E50, Operation: "LINK", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFF8, Match: 0x4E58, Operation: "UNLK", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFF0, Match: 0x4E40, Operation: "TRAP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFF0, Match: 0x4E60, Operation: "MOVE_USP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFFC0, Match: 0x40C0, Operation: "MOVE_FROM_SR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFFC0, Match: 0x44C0, Operation: "MOVE_TO_CCR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xFFC0, Match: 0x46C0, Operation: "MOVE_TO_SR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xFFC0, Match: 0x4800, Operation: "NBCD", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFFC0, Match: 0x4840, Operation: "PEA", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Control),
            FieldOp(Mask: 0xFFC0, Match: 0x4AC0, Operation: "TAS", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFFC0, Match: 0x4EC0, Operation: "JMP", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Control),
            FieldOp(Mask: 0xFFC0, Match: 0x4E80, Operation: "JSR", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Control),
            FieldOp(Mask: 0xFFB8, Match: 0x4880, Operation: "EXT", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xFB80, Match: 0x4880, Operation: "MOVEM", SizeShift: 6, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Control),
            FieldOp(Mask: 0xF1C0, Match: 0x4180, Operation: "CHK", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1C0, Match: 0x41C0, Operation: "LEA", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Control),
            FieldOp(Mask: 0xFF00, Match: 0x4200, Operation: "CLR", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x4000, Operation: "NEGX", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x4400, Operation: "NEG", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x4600, Operation: "NOT", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xFF00, Match: 0x4A00, Operation: "TST", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xF0F8, Match: 0x50C8, Operation: "DBcc", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF0C0, Match: 0x50C0, Operation: "Scc", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xF100, Match: 0x5000, Operation: "ADDQ", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Alterable),
            FieldOp(Mask: 0xF100, Match: 0x5100, Operation: "SUBQ", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.Alterable),
            FieldOp(Mask: 0xF000, Match: 0x6000, Operation: "Bcc", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF100, Match: 0x7000, Operation: "MOVEQ", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF1C0, Match: 0x80C0, Operation: "DIVU", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1C0, Match: 0x81C0, Operation: "DIVS", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1F0, Match: 0x8100, Operation: "SBCD", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF000, Match: 0x8000, Operation: "OR", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF0C0, Match: 0x90C0, Operation: "SUBA", SizeShift: 8, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF130, Match: 0x9100, Operation: "SUBX", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF000, Match: 0x9000, Operation: "SUB", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF0C0, Match: 0xB0C0, Operation: "CMPA", SizeShift: 8, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF138, Match: 0xB108, Operation: "CMPM", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF100, Match: 0xB100, Operation: "EOR", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAlterable),
            FieldOp(Mask: 0xF100, Match: 0xB000, Operation: "CMP", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1C0, Match: 0xC0C0, Operation: "MULU", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1C0, Match: 0xC1C0, Operation: "MULS", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF1F0, Match: 0xC100, Operation: "ABCD", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF130, Match: 0xC100, Operation: "EXG", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF000, Match: 0xC000, Operation: "AND", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF0C0, Match: 0xD0C0, Operation: "ADDA", SizeShift: 8, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF130, Match: 0xD100, Operation: "ADDX", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF000, Match: 0xD000, Operation: "ADD", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.DataAddressing),
            FieldOp(Mask: 0xF8C0, Match: 0xE0C0, Operation: "SHIFT_MEM", SizeShift: 0, SizeWidth: 1, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.MemoryAlterable),
            FieldOp(Mask: 0xF018, Match: 0xE000, Operation: "ASLR_REG", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF018, Match: 0xE008, Operation: "LSLR_REG", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF018, Match: 0xE010, Operation: "ROXLR_REG", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
            FieldOp(Mask: 0xF018, Match: 0xE018, Operation: "ROLR_REG", SizeShift: 6, SizeWidth: 2, SizeEncoding: SizeEncoding.Standard, EaShift: 0, LegalEa: EaCategory.All),
        ]);

    public static readonly InstructionDef[] Instructions = [];
}
