using System.Globalization;
using System.Text;

namespace CpuEmulator.Profiler;

/// <summary>Renders bench/results/profiles/INDEX.md — the human-readable backlog surface (ADR 0022 §4.2):
/// per system, the headline real-time ratio per tier, the chainEdges:dispatcher ratio, recompiles/
/// evictions, block-cache hit/miss, and the top hot-ops. A developer/agent reads this to rank the
/// optimization backlog.</summary>
public static class IndexWriter
{
    public static string Render(IReadOnlyList<SystemProfile> profiles, string commit, HostInfo host)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Performance profiles — INDEX (ADR 0022 item A)");
        sb.AppendLine();
        sb.AppendLine($"- Generated: {DateTime.UtcNow:o}");
        sb.AppendLine($"- Commit: `{commit}`");
        sb.AppendLine($"- Host: {host.Os} / .NET {host.Dotnet}");
        sb.AppendLine($"- Profiles: {profiles.Count}");
        sb.AppendLine();
        sb.AppendLine("Generated by `bench/profiler` (a dev tool, not in the shipping/test graph). Each row is the");
        sb.AppendLine("headline of one `bench/results/profiles/<system>/<workload>.json`. `rtRatio` = cyclesPerSecond ÷");
        sb.AppendLine("nominalClockHz (`—` when the board declares no clock, e.g. the kernels). `chain:disp` = the");
        sb.AppendLine("ADR-0012 floor signal (ChainEdgesTaken : DispatcherEntries — high means chaining carries the hot");
        sb.AppendLine("path). `recmp/evic` = recompile/eviction churn (SMC/bank thrash). `hit/miss` = block-cache.");
        sb.AppendLine();

        // ── throughput + counters table ──
        sb.AppendLine("## Throughput + JIT counters");
        sb.AppendLine();
        sb.AppendLine("| system / workload | tier | cyc/s | rtRatio | compiles | recmp/evic | smcHot | chainEdges | dispEntries | chain:disp | hit/miss |");
        sb.AppendLine("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|");
        foreach (var p in profiles)
        {
            if (p.Tiers.Interpreter is { } it)
            {
                sb.AppendLine($"| {p.System} / {p.Workload} | interp | {Sci(it.CyclesPerSecond)} | {Ratio(it.RealtimeRatio)} | — | — | — | — | — | — | — |");
            }
            if (p.Tiers.Jit is { } jt)
            {
                string chainDisp = jt.DispatcherEntries > 0
                    ? (jt.ChainEdgesTaken / (double)jt.DispatcherEntries).ToString("F1", CultureInfo.InvariantCulture)
                    : (jt.ChainEdgesTaken > 0 ? "inf" : "—");
                sb.AppendLine($"| {p.System} / {p.Workload} | jit | {Sci(jt.CyclesPerSecond)} | {Ratio(jt.RealtimeRatio)} | " +
                              $"{jt.CompileCount} | {jt.TotalRecompiles}/{jt.TotalEvictions} | {jt.SmcHotPcCount} | " +
                              $"{jt.ChainEdgesTaken:N0} | {jt.DispatcherEntries:N0} | {chainDisp} | {jt.BlockCacheHits:N0}/{jt.BlockCacheMisses:N0} |");
            }
        }
        sb.AppendLine();

        // ── top hot-ops per system (interpreter tier, where captured) ──
        sb.AppendLine("## Top hot-ops (interpreter tier)");
        sb.AppendLine();
        foreach (var p in profiles)
        {
            var hot = p.Tiers.Interpreter?.HotOps;
            if (hot is null || hot.Count == 0)
            {
                sb.AppendLine($"- **{p.System} / {p.Workload}**: (no hot-op histogram — see profile notes)");
                continue;
            }
            string top = string.Join(", ", hot.Take(8).Select(h => $"{h.Mnemonic} {h.Pct:F1}%"));
            sb.AppendLine($"- **{p.System} / {p.Workload}**: {top}");
        }
        sb.AppendLine();

        sb.AppendLine("## Notes");
        sb.AppendLine();
        sb.AppendLine("- `fallbackByOpcode` is empty and `emitCoverage` is null in every profile — full execution-weighted");
        sb.AppendLine("  per-opcode fallback attribution + emit coverage is ADR 0022 item D (a follow-on), deferred.");
        sb.AppendLine("- `perPeripheralFrameCostNs` is null — the SAMPLED per-peripheral stopwatch is ADR 0022 item F infra, deferred.");
        sb.AppendLine("- Dual-CPU SoftCard boots capture throughput + counters via bulk Run; the per-instruction hot-op");
        sb.AppendLine("  histogram is skipped for them (stepping the primary directly bypasses coprocessor arbitration).");
        sb.AppendLine("- Apple Pascal is interpreter-only (`Pascal.CreateBoard` takes no ExecutionTier).");
        return sb.ToString();
    }

    private static string Sci(double v) => v.ToString("0.00e+0", CultureInfo.InvariantCulture);

    private static string Ratio(double? r)
        => r is double v ? v.ToString("F3", CultureInfo.InvariantCulture) + "x" : "—";
}
