using CpuEmulator.Core;

namespace CpuEmulator.Cpus.Z80;

public sealed partial class Z80Cpu
{
    /// <summary>The Io-bus (16-bit port space) the JIT dispatcher routes Port-op callouts to (5-3b). In
    /// 5-3a every Z80 op falls back to the interpreter Step (which writes the ports directly), but the
    /// <see cref="CpuEmulator.Jit"/> <c>JittedCpu&lt;Z80Cpu&gt;</c> ctor still needs the bus handle. The Z80
    /// HAS an Io space (unlike the 6502), so this is a real second callout bus.</summary>
    public IAddressSpace IoBus => _io;

    /// <summary>The cycle-charge seam the JIT's emitted fastmem fast path calls (the 6502 has the same
    /// internal <c>AdvanceCycles</c> on its hand-written partial). The generated <c>JitTarget</c> resolves
    /// this by name (NonPublic | Instance). NO emitted Z80 op calls it in 5-3a (every op falls back, and
    /// the fallback uses the CycleCount delta), but the handle must RESOLVE — a recorded J1 finding: the
    /// Z80's generated cycle bookkeeping increments <c>_cycles</c> inline, so the per-CPU seam supplies this
    /// named charge method (the 6502 convention) for the emitted arms 5-3b adds.</summary>
    internal void AdvanceCycles(long n) => _cycles += n;

    // The per-CPU IJitTarget (J1) is now GENERATED by CpuEmitter (EmitJitTarget) as Z80Cpu.JitTarget —
    // the data-driven replacement for the Task-1 hand-written Z80JitTarget stub (removed here). This
    // partial keeps only the non-generated seam: the IoBus accessor + the AdvanceCycles charge method.
}
