// <auto-generated>
//   Tool    : CpuEmulator.SpecImporter
//   Dataset : tools/CpuEmulator.SpecImporter/data/z80-opcodes.json
//   Semantics: tools/CpuEmulator.SpecImporter/data/z80-semantics.json
//   Total rows : 698
//   Regenerate :
//     dotnet run --project tools/CpuEmulator.SpecImporter -- \
//       --dataset tools/CpuEmulator.SpecImporter/data/z80-opcodes.json \
//       --semantics tools/CpuEmulator.SpecImporter/data/z80-semantics.json \
//       --out src/CpuEmulator.Cpus.Z80/Z80Spec.cs
// </auto-generated>

using CpuEmulator.Core.Specification;
using static CpuEmulator.Core.Specification.Spec;

namespace CpuEmulator.Cpus.Z80;

[CpuSpecification("z80")]
public static class Z80Spec
{
    public static readonly RegisterDef[] Registers =
    [
        new("A", 8),
        new("F", 8, RegisterRole.Status),
        new("B", 8),
        new("C", 8),
        new("D", 8),
        new("E", 8),
        new("H", 8),
        new("L", 8),
        new("A_", 8),
        new("F_", 8),
        new("B_", 8),
        new("C_", 8),
        new("D_", 8),
        new("E_", 8),
        new("H_", 8),
        new("L_", 8),
        new("I", 8),
        new("R", 8),
        new("IX", 16),
        new("IY", 16),
        new("SP", 16, RegisterRole.StackPointer),
        new("PC", 16, RegisterRole.ProgramCounter),
        new("AF", 16, HighHalf: "A", LowHalf: "F"),
        new("BC", 16, HighHalf: "B", LowHalf: "C"),
        new("DE", 16, HighHalf: "D", LowHalf: "E"),
        new("HL", 16, HighHalf: "H", LowHalf: "L"),
        new("AF_", 16, HighHalf: "A_", LowHalf: "F_"),
        new("BC_", 16, HighHalf: "B_", LowHalf: "C_"),
        new("DE_", 16, HighHalf: "D_", LowHalf: "E_"),
        new("HL_", 16, HighHalf: "H_", LowHalf: "L_"),
    ];

    public static readonly DecodeStructure Decode = new(
        Prefixes: [new PrefixByte(0xED)],
        ModRmOpcodes: [],
        SubFieldOpcodes: []);

    public static readonly InstructionDef[] Instructions =
    [
        Insn(0x00, "NOP", AddrMode.Implied, []),
        // TODO(semantics): 0x07 RLCA Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x08 EX Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x0F RRCA Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x10 DJNZ RelativeJump — awaiting micro-op vocabulary
        // TODO(semantics): 0x17 RLA Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x18 JR RelativeJump — awaiting micro-op vocabulary
        // TODO(semantics): 0x1F RRA Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x27 DAA Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x2F CPL Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x37 SCF Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x3F CCF Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0x01 LD ImmediateExtended — awaiting micro-op vocabulary
        // TODO(semantics): 0x11 LD ImmediateExtended — awaiting micro-op vocabulary
        // TODO(semantics): 0x21 LD ImmediateExtended — awaiting micro-op vocabulary
        // TODO(semantics): 0x31 LD ImmediateExtended — awaiting micro-op vocabulary
        // TODO(mode): 0x09 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x19 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x29 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x39 ADD Register — awaiting AddrMode support
        // TODO(semantics): 0x03 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x0B DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x13 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x1B DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x23 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x2B DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x33 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x3B DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x04 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x0C INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x14 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x1C INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x24 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x2C INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x34 INC RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x3C INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x05 DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x0D DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x15 DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x1D DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x25 DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x2D DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x35 DEC RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x3D DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x06 LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x0E LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x16 LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x1E LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x26 LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x2E LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x36 LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x3E LD Immediate — awaiting micro-op vocabulary
        // TODO(semantics): 0x02 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x12 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x22 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0x32 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0x0A LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x1A LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x2A LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0x3A LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0x20 JR RelativeJump — awaiting micro-op vocabulary
        // TODO(semantics): 0x28 JR RelativeJump — awaiting micro-op vocabulary
        // TODO(semantics): 0x30 JR RelativeJump — awaiting micro-op vocabulary
        // TODO(semantics): 0x38 JR RelativeJump — awaiting micro-op vocabulary
        // TODO(semantics): 0x40 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x41 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x42 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x43 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x44 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x45 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x46 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x47 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x48 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x49 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x4A LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x4B LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x4C LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x4D LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x4E LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x4F LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x50 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x51 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x52 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x53 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x54 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x55 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x56 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x57 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x58 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x59 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x5A LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x5B LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x5C LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x5D LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x5E LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x5F LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x60 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x61 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x62 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x63 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x64 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x65 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x66 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x67 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x68 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x69 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x6A LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x6B LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x6C LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x6D LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x6E LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x6F LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x70 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x71 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x72 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x73 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x74 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x75 LD RegisterIndirect — awaiting micro-op vocabulary
        Insn(0x76, "HALT", AddrMode.Implied, [Halt()]),
        // TODO(semantics): 0x77 LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x78 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x79 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x7A LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x7B LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x7C LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x7D LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0x7E LD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0x7F LD Register — awaiting micro-op vocabulary
        // TODO(mode): 0x80 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x81 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x82 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x83 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x84 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x85 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x86 ADD RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0x87 ADD Register — awaiting AddrMode support
        // TODO(mode): 0x88 ADC Register — awaiting AddrMode support
        // TODO(mode): 0x89 ADC Register — awaiting AddrMode support
        // TODO(mode): 0x8A ADC Register — awaiting AddrMode support
        // TODO(mode): 0x8B ADC Register — awaiting AddrMode support
        // TODO(mode): 0x8C ADC Register — awaiting AddrMode support
        // TODO(mode): 0x8D ADC Register — awaiting AddrMode support
        // TODO(mode): 0x8E ADC RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0x8F ADC Register — awaiting AddrMode support
        // TODO(mode): 0x90 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x91 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x92 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x93 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x94 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x95 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x96 SUB RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0x97 SUB Register — awaiting AddrMode support
        // TODO(mode): 0x98 SBC Register — awaiting AddrMode support
        // TODO(mode): 0x99 SBC Register — awaiting AddrMode support
        // TODO(mode): 0x9A SBC Register — awaiting AddrMode support
        // TODO(mode): 0x9B SBC Register — awaiting AddrMode support
        // TODO(mode): 0x9C SBC Register — awaiting AddrMode support
        // TODO(mode): 0x9D SBC Register — awaiting AddrMode support
        // TODO(mode): 0x9E SBC RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0x9F SBC Register — awaiting AddrMode support
        // TODO(mode): 0xA0 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA1 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA2 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA3 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA4 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA5 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA6 AND RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0xA7 AND Register — awaiting AddrMode support
        // TODO(mode): 0xA8 XOR Register — awaiting AddrMode support
        // TODO(mode): 0xA9 XOR Register — awaiting AddrMode support
        // TODO(mode): 0xAA XOR Register — awaiting AddrMode support
        // TODO(mode): 0xAB XOR Register — awaiting AddrMode support
        // TODO(mode): 0xAC XOR Register — awaiting AddrMode support
        // TODO(mode): 0xAD XOR Register — awaiting AddrMode support
        // TODO(mode): 0xAE XOR RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0xAF XOR Register — awaiting AddrMode support
        // TODO(mode): 0xB0 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB1 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB2 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB3 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB4 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB5 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB6 OR RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0xB7 OR Register — awaiting AddrMode support
        // TODO(mode): 0xB8 CP Register — awaiting AddrMode support
        // TODO(mode): 0xB9 CP Register — awaiting AddrMode support
        // TODO(mode): 0xBA CP Register — awaiting AddrMode support
        // TODO(mode): 0xBB CP Register — awaiting AddrMode support
        // TODO(mode): 0xBC CP Register — awaiting AddrMode support
        // TODO(mode): 0xBD CP Register — awaiting AddrMode support
        // TODO(mode): 0xBE CP RegisterIndirect — awaiting AddrMode support
        // TODO(mode): 0xBF CP Register — awaiting AddrMode support
        // TODO(semantics): 0xC1 POP Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xD1 POP Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xE1 POP Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xF1 POP Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xC5 PUSH Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xD5 PUSH Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xE5 PUSH Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xF5 PUSH Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xC3 JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xC9 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xCD CALL ExtendedAddress — awaiting micro-op vocabulary
        Insn(0xC6, "ADD", AddrMode.Immediate, [Adc()]),
        Insn(0xCE, "ADC", AddrMode.Immediate, [Adc()]),
        Insn(0xD6, "SUB", AddrMode.Immediate, [Sbc()]),
        Insn(0xDE, "SBC", AddrMode.Immediate, [Sbc()]),
        Insn(0xE6, "AND", AddrMode.Immediate, [And()]),
        Insn(0xEE, "XOR", AddrMode.Immediate, [Eor()]),
        Insn(0xF6, "OR", AddrMode.Immediate, [Ora()]),
        Insn(0xFE, "CP", AddrMode.Immediate, [Compare("A")]),
        Insn(0xD3, "OUT", AddrMode.IoPortImmediate, [PortOut("A")]),
        Insn(0xDB, "IN", AddrMode.IoPortImmediate, [PortIn("A")]),
        // TODO(semantics): 0xD9 EXX Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xE3 EX RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xE9 JP RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xEB EX Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xF3 DI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xFB EI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xF9 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xC0 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xC8 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xD0 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xD8 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xE0 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xE8 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xF0 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xF8 RET Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xC2 JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xCA JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xD2 JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xDA JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xE2 JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xEA JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xF2 JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xFA JP ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xC4 CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xCC CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xD4 CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xDC CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xE4 CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xEC CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xF4 CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xFC CALL ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xC7 RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xCF RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xD7 RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xDF RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xE7 RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xEF RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xF7 RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xFF RST Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x00 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x01 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x02 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x03 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x04 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x05 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x06 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x07 RLC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x08 RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x09 RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x0A RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x0B RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x0C RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x0D RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x0E RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x0F RRC Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x10 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x11 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x12 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x13 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x14 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x15 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x16 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x17 RL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x18 RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x19 RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x1A RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x1B RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x1C RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x1D RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x1E RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x1F RR Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x20 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x21 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x22 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x23 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x24 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x25 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x26 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x27 SLA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x28 SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x29 SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x2A SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x2B SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x2C SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x2D SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x2E SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x2F SRA Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x38 SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x39 SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x3A SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x3B SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x3C SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x3D SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x3E SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x3F SRL Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x40 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x41 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x42 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x43 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x44 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x45 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x46 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x47 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x48 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x49 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x4A BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x4B BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x4C BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x4D BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x4E BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x4F BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x50 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x51 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x52 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x53 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x54 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x55 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x56 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x57 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x58 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x59 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x5A BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x5B BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x5C BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x5D BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x5E BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x5F BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x60 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x61 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x62 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x63 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x64 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x65 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x66 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x67 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x68 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x69 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x6A BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x6B BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x6C BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x6D BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x6E BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x6F BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x70 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x71 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x72 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x73 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x74 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x75 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x76 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x77 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x78 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x79 BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x7A BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x7B BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x7C BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x7D BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x7E BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x7F BIT Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x80 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x81 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x82 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x83 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x84 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x85 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x86 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x87 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x88 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x89 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x8A RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x8B RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x8C RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x8D RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x8E RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x8F RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x90 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x91 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x92 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x93 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x94 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x95 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x96 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x97 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x98 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x99 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x9A RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x9B RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x9C RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x9D RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x9E RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0x9F RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA0 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA1 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA2 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA3 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA4 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA5 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA6 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA7 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA8 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xA9 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xAA RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xAB RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xAC RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xAD RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xAE RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xAF RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB0 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB1 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB2 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB3 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB4 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB5 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB6 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB7 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB8 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xB9 RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xBA RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xBB RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xBC RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xBD RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xBE RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xBF RES Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC0 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC1 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC2 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC3 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC4 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC5 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC6 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC7 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC8 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xC9 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xCA SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xCB SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xCC SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xCD SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xCE SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xCF SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD0 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD1 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD2 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD3 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD4 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD5 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD6 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD7 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD8 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xD9 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xDA SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xDB SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xDC SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xDD SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xDE SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xDF SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE0 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE1 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE2 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE3 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE4 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE5 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE6 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE7 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE8 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xE9 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xEA SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xEB SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xEC SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xED SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xEE SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xEF SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF0 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF1 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF2 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF3 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF4 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF5 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF6 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF7 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF8 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xF9 SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xFA SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xFB SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xFC SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xFD SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xFE SET Bit — awaiting micro-op vocabulary
        // TODO(semantics): 0xCB:0xFF SET Bit — awaiting micro-op vocabulary
        // TODO(mode): 0xED:0x40 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x48 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x50 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x58 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x60 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x68 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x78 IN Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x41 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x49 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x51 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x59 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x61 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x69 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x79 OUT Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x42 SBC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x52 SBC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x62 SBC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x72 SBC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x4A ADC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x5A ADC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x6A ADC Register — awaiting AddrMode support
        // TODO(mode): 0xED:0x7A ADC Register — awaiting AddrMode support
        // TODO(semantics): 0xED:0x43 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x53 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x63 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x73 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x4B LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x5B LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x6B LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x7B LD ExtendedAddress — awaiting micro-op vocabulary
        Insn(0xED, 0x44, "NEG", AddrMode.Implied, []),
        // TODO(semantics): 0xED:0x45 RETN Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x4D RETI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x46 IM Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x56 IM Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x5E IM Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x47 LD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x4F LD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x57 LD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x5F LD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x67 RRD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0x6F RLD RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xA0 LDI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xA1 CPI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xA2 INI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xA3 OUTI Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xA8 LDD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xA9 CPD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xAA IND Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xAB OUTD Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xB0 LDIR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xB1 CPIR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xB2 INIR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xB3 OTIR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xB8 LDDR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xB9 CPDR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xBA INDR Implied — awaiting micro-op vocabulary
        // TODO(semantics): 0xED:0xBB OTDR Implied — awaiting micro-op vocabulary
        // TODO(mode): 0xDD:0x09 ADD Register — awaiting AddrMode support
        // TODO(mode): 0xDD:0x19 ADD Register — awaiting AddrMode support
        // TODO(mode): 0xDD:0x29 ADD Register — awaiting AddrMode support
        // TODO(mode): 0xDD:0x39 ADD Register — awaiting AddrMode support
        // TODO(semantics): 0xDD:0x21 LD ImmediateExtended — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x22 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x23 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x2A LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x2B DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x34 INC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x35 DEC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x36 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0xE1 POP Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0xE3 EX RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0xE5 PUSH Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0xE9 JP RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0xF9 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x46 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x4E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x56 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x5E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x66 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x6E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x7E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x70 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x71 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x72 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x73 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x74 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x75 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDD:0x77 LD Indexed — awaiting micro-op vocabulary
        // TODO(mode): 0xDD:0x86 ADD Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0x8E ADC Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0x96 SUB Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0x9E SBC Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0xA6 AND Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0xAE XOR Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0xB6 OR Indexed — awaiting AddrMode support
        // TODO(mode): 0xDD:0xBE CP Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0x09 ADD Register — awaiting AddrMode support
        // TODO(mode): 0xFD:0x19 ADD Register — awaiting AddrMode support
        // TODO(mode): 0xFD:0x29 ADD Register — awaiting AddrMode support
        // TODO(mode): 0xFD:0x39 ADD Register — awaiting AddrMode support
        // TODO(semantics): 0xFD:0x21 LD ImmediateExtended — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x22 LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x23 INC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x2A LD ExtendedAddress — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x2B DEC Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x34 INC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x35 DEC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x36 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0xE1 POP Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0xE3 EX RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0xE5 PUSH Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0xE9 JP RegisterIndirect — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0xF9 LD Register — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x46 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x4E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x56 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x5E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x66 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x6E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x7E LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x70 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x71 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x72 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x73 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x74 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x75 LD Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFD:0x77 LD Indexed — awaiting micro-op vocabulary
        // TODO(mode): 0xFD:0x86 ADD Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0x8E ADC Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0x96 SUB Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0x9E SBC Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0xA6 AND Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0xAE XOR Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0xB6 OR Indexed — awaiting AddrMode support
        // TODO(mode): 0xFD:0xBE CP Indexed — awaiting AddrMode support
        // TODO(semantics): 0xDDCB:0x06 RLC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x0E RRC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x16 RL Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x1E RR Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x26 SLA Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x2E SRA Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x3E SRL Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x46 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x4E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x56 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x5E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x66 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x6E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x76 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x7E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x86 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x8E RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x96 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0x9E RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xA6 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xAE RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xB6 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xBE RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xC6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xCE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xD6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xDE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xE6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xEE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xF6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xDDCB:0xFE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x06 RLC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x0E RRC Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x16 RL Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x1E RR Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x26 SLA Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x2E SRA Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x3E SRL Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x46 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x4E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x56 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x5E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x66 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x6E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x76 BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x7E BIT Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x86 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x8E RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x96 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0x9E RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xA6 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xAE RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xB6 RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xBE RES Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xC6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xCE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xD6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xDE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xE6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xEE SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xF6 SET Indexed — awaiting micro-op vocabulary
        // TODO(semantics): 0xFDCB:0xFE SET Indexed — awaiting micro-op vocabulary
    ];
}
