using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CpuEmulator.Generators;

internal static class CpuEmitter
{
    public static string Emit(SpecModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CpuEmulator.Generators from the CPU specification.");
        sb.AppendLine("// The hand-written partial MUST provide: a constructor, Reset(),");
        sb.AppendLine("// SetIrqLine(bool), SetNmiLine(bool), byte ReadBus(uint address)");
        sb.AppendLine("// (which increments _cycles), WriteBus(uint, byte) (which increments _cycles),");
        sb.AppendLine("// and HandleUndefinedOpcode(byte opcode).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {model.CpuName} : CpuEmulator.Core.ICpuCore");
        sb.AppendLine("{");
        sb.AppendLine($"    public string Architecture => {SymbolDisplay.FormatLiteral(model.Architecture, quote: true)};");
        sb.AppendLine();
        sb.AppendLine("    private long _cycles;");
        sb.AppendLine("    public long CycleCount => _cycles;");
        EmitBody(sb, model);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBody(StringBuilder sb, SpecModel model)
    {
        sb.AppendLine();
        foreach (var register in model.Registers)
            sb.AppendLine($"    public {(register.Bits == 8 ? "byte" : "ushort")} {register.Name};");

        string nameList = string.Join(", ", model.Registers.Select(r => $"\"{r.Name}\""));
        sb.AppendLine();
        sb.AppendLine($"    private static readonly string[] s_registerNames = [{nameList}];");
        sb.AppendLine("    public System.Collections.Generic.IReadOnlyList<string> RegisterNames => s_registerNames;");

        sb.AppendLine();
        sb.AppendLine("    public ulong GetRegister(string name) => name switch");
        sb.AppendLine("    {");
        foreach (var register in model.Registers)
            sb.AppendLine($"        \"{register.Name}\" => {register.Name},");
        sb.AppendLine("        _ => throw new System.ArgumentException($\"Unknown register '{name}'.\", nameof(name)),");
        sb.AppendLine("    };");

        sb.AppendLine();
        sb.AppendLine("    public void SetRegister(string name, ulong value)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (name)");
        sb.AppendLine("        {");
        foreach (var register in model.Registers)
        {
            string cast = register.Bits == 8 ? "byte" : "ushort";
            sb.AppendLine($"            case \"{register.Name}\": {register.Name} = unchecked(({cast})value); break;");
        }
        sb.AppendLine("            default: throw new System.ArgumentException($\"Unknown register '{name}'.\", nameof(name));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        EmitExecution(sb, model);
        EmitDisassembler(sb, model);
    }

    private static void EmitExecution(StringBuilder sb, SpecModel model)
    {
        var pcRegister = model.Registers.First(r => r.Role == "ProgramCounter");
        string pc = pcRegister.Name;
        string pcType = pcRegister.Bits == 8 ? "byte" : "ushort";

        // Status register (for SetNZ emission)
        var statusRegister = model.Registers.FirstOrDefault(r => r.Role == "Status");
        string? statusReg = statusRegister?.Name;

        sb.AppendLine();
        sb.AppendLine("    // Instruction table parsed from the spec:");
        foreach (var instruction in model.Instructions)
            sb.AppendLine($"    //   0x{instruction.Opcode:X2} {instruction.Mnemonic} {instruction.Mode}");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Execute one instruction. Always advances CycleCount by at least one.</summary>");
        sb.AppendLine("    public void Step()");
        sb.AppendLine("    {");
        sb.AppendLine($"        byte opcode = ReadBus({pc});");
        sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
        sb.AppendLine("        Execute(opcode);");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    public void Run(ref long cycleBudget)");
        sb.AppendLine("    {");
        sb.AppendLine("        while (cycleBudget > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            long before = _cycles;");
        sb.AppendLine("            Step();");
        sb.AppendLine("            cycleBudget -= _cycles - before;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    private void Execute(byte opcode)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (opcode)");
        sb.AppendLine("        {");
        foreach (var instruction in model.Instructions)
            sb.AppendLine($"            case 0x{instruction.Opcode:X2}: Op{instruction.Opcode:X2}(); break;");
        sb.AppendLine("            default:");
        sb.AppendLine("                HandleUndefinedOpcode(opcode);");
        sb.AppendLine("                break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        // Emit all per-opcode methods
        foreach (var instruction in model.Instructions)
            EmitOpcodeMethod(sb, instruction, pc, pcType, statusReg);
    }

    private static void EmitOpcodeMethod(
        StringBuilder sb,
        InstructionModel instruction,
        string pc,
        string pcType,
        string? statusReg)
    {
        // Classification is carried on the model — the parser classified it once (CPUGEN010).
        // The emitter consumes instruction.Class directly; no parallel classifier here.
        InstructionClass opClass = instruction.Class;
        int cycleCount = ComputeCycles(instruction.Mode, opClass);
        string cycleStr = (opClass == InstructionClass.Branch) ? "2-4 cycles"
            : (instruction.Mode is "AbsoluteX" or "AbsoluteY" or "IndirectY"
               && opClass is InstructionClass.Load) ? $"{cycleCount}-{cycleCount + 1} cycles (+1 on page cross)"
            : $"{cycleCount} cycles";

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>0x{instruction.Opcode:X2} {instruction.Mnemonic} {instruction.Mode} — {cycleStr}.</summary>");
        sb.AppendLine($"    private void Op{instruction.Opcode:X2}()");
        sb.AppendLine("    {");

        switch (opClass)
        {
            case InstructionClass.Load:
                EmitLoadBody(sb, instruction, pc, pcType, statusReg);
                break;
            case InstructionClass.Register:
                EmitRegisterBody(sb, instruction, pc, statusReg);
                break;
            case InstructionClass.Store:
                EmitStoreBody(sb, instruction, pc, pcType);
                break;
            case InstructionClass.Jump:
                EmitJumpBody(sb, instruction, pc, pcType);
                break;
            case InstructionClass.Branch:
                EmitBranchBody(sb, instruction, pc, pcType, statusReg);
                break;
            default:
                throw new System.InvalidOperationException(
                    $"emitter has no body template for class '{opClass}' (opcode 0x{instruction.Opcode:X2})");
        }

        sb.AppendLine("    }");
    }

    private static int ComputeCycles(string mode, InstructionClass opClass) => (mode, opClass) switch
    {
        // 1 (opcode fetch) + template cycles
        ("Implied", _) => 2,                                   // +1 dummy read
        ("Immediate", _) => 2,                                 // +1 operand read
        ("ZeroPage", InstructionClass.Load) => 3,              // +1 addr +1 data
        ("ZeroPage", InstructionClass.Store) => 3,             // +1 addr +1 write
        ("ZeroPageX", InstructionClass.Load) => 4,             // +1 addr +1 dummy +1 data
        ("ZeroPageX", InstructionClass.Store) => 4,            // +1 addr +1 dummy +1 write
        ("ZeroPageY", InstructionClass.Load) => 4,             // +1 addr +1 dummy +1 data
        ("ZeroPageY", InstructionClass.Store) => 4,            // +1 addr +1 dummy +1 write
        ("Absolute", InstructionClass.Load) => 4,              // +1 lo +1 hi +1 data
        ("Absolute", InstructionClass.Store) => 4,             // +1 lo +1 hi +1 write
        ("Absolute", InstructionClass.Jump) => 3,              // +1 lo +1 hi
        ("AbsoluteX", InstructionClass.Load) => 4,             // 4-5 (+1 cross) — variable
        ("AbsoluteX", InstructionClass.Store) => 5,            // always 5 (dummy read)
        ("AbsoluteY", InstructionClass.Load) => 4,             // 4-5 (+1 cross) — variable
        ("AbsoluteY", InstructionClass.Store) => 5,            // always 5 (dummy read)
        ("IndirectX", InstructionClass.Load) => 6,             // 6 cycles
        ("IndirectX", InstructionClass.Store) => 6,            // 6 cycles
        ("IndirectY", InstructionClass.Load) => 5,             // 5-6 (+1 cross) — variable
        ("IndirectY", InstructionClass.Store) => 6,            // always 6 (dummy read)
        ("Indirect", InstructionClass.Jump) => 5,              // 5 cycles (JMP indirect)
        ("Accumulator", _) => 2,                               // +1 dummy read
        ("Relative", InstructionClass.Branch) => 0,            // variable: 2/3/4 — doc string says "2-4 cycles"
        _ => throw new System.InvalidOperationException(
            $"emitter has no cycle count for mode '{mode}' / class '{opClass}'"),
    };

    // ---- Load class ----

    private static void EmitLoadBody(
        StringBuilder sb,
        InstructionModel instruction,
        string pc,
        string pcType,
        string? statusReg)
    {
        // First op is Load(target)
        string target = instruction.Ops[0].Args[0]; // register name

        switch (instruction.Mode)
        {
            case "Immediate":
                sb.AppendLine($"        byte data = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        {target} = data;");
                break;
            case "ZeroPage":
                sb.AppendLine($"        uint addr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        byte data = ReadBus(addr);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "ZeroPageX":
                sb.AppendLine($"        uint addr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        _ = ReadBus(addr); // dummy read at unindexed zp");
                sb.AppendLine($"        byte data = ReadBus((addr + X) & 0xFF);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "ZeroPageY":
                sb.AppendLine($"        uint addr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        _ = ReadBus(addr); // dummy read at unindexed zp");
                sb.AppendLine($"        byte data = ReadBus((addr + Y) & 0xFF);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "Absolute":
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ea = lo | (hi << 8);");
                sb.AppendLine($"        byte data = ReadBus(ea);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "AbsoluteX":
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ea = ((lo | (hi << 8)) + X) & 0xFFFF;");
                sb.AppendLine($"        byte data = ReadBus((hi << 8) | ((lo + X) & 0xFF));");
                sb.AppendLine($"        if (((lo + X) & 0x100) != 0)");
                sb.AppendLine($"            data = ReadBus(ea);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "AbsoluteY":
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ea = ((lo | (hi << 8)) + Y) & 0xFFFF;");
                sb.AppendLine($"        byte data = ReadBus((hi << 8) | ((lo + Y) & 0xFF));");
                sb.AppendLine($"        if (((lo + Y) & 0x100) != 0)");
                sb.AppendLine($"            data = ReadBus(ea);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "IndirectX":
                sb.AppendLine($"        uint ptr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        _ = ReadBus(ptr); // dummy read at unindexed ptr");
                sb.AppendLine($"        uint lo = ReadBus((ptr + X) & 0xFF);");
                sb.AppendLine($"        uint hi = ReadBus((ptr + X + 1) & 0xFF);");
                sb.AppendLine($"        uint ea = lo | (hi << 8);");
                sb.AppendLine($"        byte data = ReadBus(ea);");
                sb.AppendLine($"        {target} = data;");
                break;
            case "IndirectY":
                sb.AppendLine($"        uint ptr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint lo = ReadBus(ptr);");
                sb.AppendLine($"        uint hi = ReadBus((ptr + 1) & 0xFF);");
                sb.AppendLine($"        uint ea = ((lo | (hi << 8)) + Y) & 0xFFFF;");
                sb.AppendLine($"        byte data = ReadBus((hi << 8) | ((lo + Y) & 0xFF));");
                sb.AppendLine($"        if (((lo + Y) & 0x100) != 0)");
                sb.AppendLine($"            data = ReadBus(ea);");
                sb.AppendLine($"        {target} = data;");
                break;
            default:
                throw new System.InvalidOperationException(
                    $"emitter has no load template for mode '{instruction.Mode}' (opcode 0x{instruction.Opcode:X2})");
        }

        // Apply remaining register ops (SetNZ etc.)
        for (int i = 1; i < instruction.Ops.Length; i++)
            EmitRegisterOp(sb, instruction.Ops[i], statusReg);
    }

    // ---- Register class (Implied mode) ----

    private static void EmitRegisterBody(
        StringBuilder sb,
        InstructionModel instruction,
        string pc,
        string? statusReg)
    {
        if (instruction.Mode != "Implied")
            throw new System.InvalidOperationException(
                $"emitter has no register template for mode '{instruction.Mode}' (opcode 0x{instruction.Opcode:X2})");

        // Dummy read at PC (does NOT increment PC)
        sb.AppendLine($"        _ = ReadBus({pc});");

        // Apply each op in order
        foreach (var op in instruction.Ops)
            EmitRegisterOp(sb, op, statusReg);
    }

    private static void EmitRegisterOp(StringBuilder sb, OpModel op, string? statusReg)
    {
        switch (op.Kind)
        {
            case "Transfer":
            {
                string src = op.Args[0];
                string dst = op.Args[1];
                sb.AppendLine($"        {dst} = {src};");
                break;
            }
            case "Increment":
            {
                string reg = op.Args[0];
                sb.AppendLine($"        {reg} = unchecked((byte)({reg} + 1));");
                break;
            }
            case "SetNZ":
            {
                string src = op.Args[0];
                string p = statusReg ?? "P";
                // P = (P & 0x7D) | (src == 0 ? 0x02 : 0x00) | (src & 0x80)
                // 0x7D = 0111_1101 clears bits 1 (Z) and 7 (N)
                sb.AppendLine($"        {p} = unchecked((byte)(({p} & 0x7D) | ({src} == 0 ? 0x02 : 0x00) | ({src} & 0x80)));");
                break;
            }
            default:
                throw new System.InvalidOperationException(
                    $"emitter has no template for register op kind '{op.Kind}'");
        }
    }

    // ---- Store class ----

    private static void EmitStoreBody(
        StringBuilder sb,
        InstructionModel instruction,
        string pc,
        string pcType)
    {
        string source = instruction.Ops[0].Args[0];

        switch (instruction.Mode)
        {
            case "ZeroPage":
                sb.AppendLine($"        uint addr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        WriteBus(addr, {source});");
                break;
            case "ZeroPageX":
                sb.AppendLine($"        uint addr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        _ = ReadBus(addr); // dummy read at unindexed zp");
                sb.AppendLine($"        WriteBus((addr + X) & 0xFF, {source});");
                break;
            case "ZeroPageY":
                sb.AppendLine($"        uint addr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        _ = ReadBus(addr); // dummy read at unindexed zp");
                sb.AppendLine($"        WriteBus((addr + Y) & 0xFF, {source});");
                break;
            case "Absolute":
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ea = lo | (hi << 8);");
                sb.AppendLine($"        WriteBus(ea, {source});");
                break;
            case "AbsoluteX":
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ea = ((lo | (hi << 8)) + X) & 0xFFFF;");
                sb.AppendLine($"        _ = ReadBus((hi << 8) | ((lo + X) & 0xFF)); // dummy read (always, right or wrong addr)");
                sb.AppendLine($"        WriteBus(ea, {source});");
                break;
            case "AbsoluteY":
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ea = ((lo | (hi << 8)) + Y) & 0xFFFF;");
                sb.AppendLine($"        _ = ReadBus((hi << 8) | ((lo + Y) & 0xFF)); // dummy read (always, right or wrong addr)");
                sb.AppendLine($"        WriteBus(ea, {source});");
                break;
            case "IndirectX":
                sb.AppendLine($"        uint ptr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        _ = ReadBus(ptr); // dummy read at unindexed ptr");
                sb.AppendLine($"        uint lo = ReadBus((ptr + X) & 0xFF);");
                sb.AppendLine($"        uint hi = ReadBus((ptr + X + 1) & 0xFF);");
                sb.AppendLine($"        uint ea = lo | (hi << 8);");
                sb.AppendLine($"        WriteBus(ea, {source});");
                break;
            case "IndirectY":
                sb.AppendLine($"        uint ptr = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint lo = ReadBus(ptr);");
                sb.AppendLine($"        uint hi = ReadBus((ptr + 1) & 0xFF);");
                sb.AppendLine($"        uint ea = ((lo | (hi << 8)) + Y) & 0xFFFF;");
                sb.AppendLine($"        _ = ReadBus((hi << 8) | ((lo + Y) & 0xFF)); // dummy read (always)");
                sb.AppendLine($"        WriteBus(ea, {source});");
                break;
            default:
                throw new System.InvalidOperationException(
                    $"emitter has no store template for mode '{instruction.Mode}' (opcode 0x{instruction.Opcode:X2})");
        }
    }

    // ---- Jump class ----

    private static void EmitJumpBody(
        StringBuilder sb,
        InstructionModel instruction,
        string pc,
        string pcType)
    {
        switch (instruction.Mode)
        {
            case "Absolute":
                // Absolute jump: fetch lo, fetch hi, set PC = ea (no data access at target)
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        {pc} = unchecked(({pcType})(lo | (hi << 8)));");
                break;
            case "Indirect":
                // JMP (ptr): 5 cycles. Reproduces the NMOS page-wrap bug:
                // a pointer at $xxFF takes its high byte from $xx00.
                sb.AppendLine($"        uint lo = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint hi = ReadBus({pc});");
                sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
                sb.AppendLine($"        uint ptr = lo | (hi << 8);");
                sb.AppendLine($"        uint target = ReadBus(ptr);");
                sb.AppendLine($"        target |= (uint)ReadBus((ptr & 0xFF00) | ((ptr + 1) & 0xFF)) << 8;");
                sb.AppendLine($"        {pc} = unchecked(({pcType})target);");
                break;
            default:
                throw new System.InvalidOperationException(
                    $"emitter has no jump template for mode '{instruction.Mode}' (opcode 0x{instruction.Opcode:X2})");
        }
    }

    // ---- Branch class ----

    // Flag name -> hardware bit position (mirrors Flag enum values)
    // MIRROR TABLES: this map mirrors CpuEmulator.Core.Specification.Flag enum bit values.
    private static int FlagBit(string flagName) => flagName switch
    {
        "C" => 0,
        "Z" => 1,
        "I" => 2,
        "D" => 3,
        "V" => 6,
        "N" => 7,
        _ => throw new System.ArgumentException($"Unknown flag '{flagName}'"),
    };

    private static void EmitBranchBody(
        StringBuilder sb,
        InstructionModel instruction,
        string pc,
        string pcType,
        string? statusReg)
    {
        if (instruction.Mode != "Relative")
            throw new System.InvalidOperationException(
                $"emitter has no branch template for mode '{instruction.Mode}' (opcode 0x{instruction.Opcode:X2})");

        string p = statusReg ?? "P";
        string flagName = instruction.Ops[0].Args[0];
        bool when = instruction.Ops[0].Args[1] == "true";
        int bit = FlagBit(flagName);
        int expectedBit = when ? 1 : 0;

        // Branch template from the plan:
        // byte offset = ReadBus(PC); PC++;
        // if (taken) {
        //   _ = ReadBus(PC);
        //   ushort target = (ushort)(PC + (sbyte)offset);
        //   if ((target & 0xFF00) != (PC & 0xFF00))
        //     _ = ReadBus((uint)((PC & 0xFF00) | (target & 0x00FF)));
        //   PC = target;
        // }
        sb.AppendLine($"        byte offset = ReadBus({pc});");
        sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
        sb.AppendLine($"        if ((({p} >> {bit}) & 1) == {expectedBit})");
        sb.AppendLine("        {");
        sb.AppendLine($"            _ = ReadBus({pc});");
        sb.AppendLine($"            ushort target = unchecked((ushort)({pc} + (sbyte)offset));");
        sb.AppendLine($"            if ((target & 0xFF00) != ({pc} & 0xFF00))");
        sb.AppendLine($"                _ = ReadBus((uint)(({pc} & 0xFF00) | (target & 0x00FF)));");
        sb.AppendLine($"            {pc} = target;");
        sb.AppendLine("        }");
    }

    // ---- Disassembler ----

    /// <summary>
    /// Emits a static <c>Disassemble</c> method that formats a decoded opcode as a human-readable
    /// string. The mnemonic whitelist (CPUGEN004: 1-8 uppercase letters/digits) guarantees every
    /// mnemonic in the table is safe for direct string interpolation — no escaping is needed.
    /// Format rules per addressing mode:
    ///   Implied   → mnemonic only        (e.g. "TAX")
    ///   Immediate → mnemonic + " #$xx"   (e.g. "LDA #$42")
    ///   ZeroPage  → mnemonic + " $xx"    (e.g. "LDA $10")
    ///   Absolute  → mnemonic + " $xxyy"  (e.g. "LDA $1234", hi then lo in address)
    ///   Relative  → mnemonic + " *±dd"   (e.g. "BNE *+5", "BNE *-4")
    ///   unknown   → "???"
    /// Relative caveat: the rendered offset is the RAW operand byte (relative to the
    /// post-operand PC), not conventional assembler <c>*</c> semantics (relative to the
    /// instruction's own address) — the two differ by the 2-byte instruction length, so
    /// bytes D0 FC render here as "BNE *-4" where a reference disassembler says "BNE *-2".
    /// Keep in mind when diffing against reference disassemblies (3b).
    /// </summary>
    private static void EmitDisassembler(StringBuilder sb, SpecModel model)
    {
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Disassemble one instruction. Returns a human-readable string.</summary>");
        sb.AppendLine("    public static string Disassemble(byte opcode, byte operandLo, byte operandHi)");
        sb.AppendLine("    {");
        sb.AppendLine("        return opcode switch");
        sb.AppendLine("        {");
        foreach (var instruction in model.Instructions)
        {
            string m = instruction.Mnemonic;
            string arm = instruction.Mode switch
            {
                "Implied" =>
                    $"            0x{instruction.Opcode:X2} => \"{m}\",",
                "Accumulator" =>
                    $"            0x{instruction.Opcode:X2} => \"{m} A\",",
                "Immediate" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} #${{operandLo:X2}}\",",
                "ZeroPage" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} ${{operandLo:X2}}\",",
                "ZeroPageX" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} ${{operandLo:X2}},X\",",
                "ZeroPageY" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} ${{operandLo:X2}},Y\",",
                "Absolute" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} ${{operandHi:X2}}{{operandLo:X2}}\",",
                "AbsoluteX" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} ${{operandHi:X2}}{{operandLo:X2}},X\",",
                "AbsoluteY" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} ${{operandHi:X2}}{{operandLo:X2}},Y\",",
                "IndirectX" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} (${{operandLo:X2}},X)\",",
                "IndirectY" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} (${{operandLo:X2}}),Y\",",
                "Indirect" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} (${{operandHi:X2}}{{operandLo:X2}})\",",
                "Relative" =>
                    $"            0x{instruction.Opcode:X2} => $\"{m} *{{(sbyte)operandLo:+0;-0}}\",",
                _ => throw new System.InvalidOperationException(
                    $"emitter has no disassembler format for mode '{instruction.Mode}' (opcode 0x{instruction.Opcode:X2})"),
            };
            sb.AppendLine(arm);
        }
        sb.AppendLine("            _ => \"???\",");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }
}
