using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CpuEmulator.Generators;

internal static class CpuEmitter
{
    public static string Emit(SpecModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CpuEmulator.Generators from the CPU specification.");
        sb.AppendLine("// The hand-written partial MUST provide: a constructor, Reset(),");
        sb.AppendLine("// SetIrqLine(bool), SetNmiLine(bool), byte ReadBus(uint address)");
        sb.AppendLine("// (which increments _cycles), and HandleUndefinedOpcode(byte opcode).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {model.CpuName} : CpuEmulator.Core.ICpuCore");
        sb.AppendLine("{");
        sb.AppendLine($"    public string Architecture => {SymbolDisplay.FormatLiteral(model.Architecture, quote: true)};");
        sb.AppendLine();
        sb.AppendLine("    internal long _cycles;");
        sb.AppendLine("    public long CycleCount => _cycles;");
        EmitBody(sb, model);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBody(StringBuilder sb, SpecModel model)
    {
        sb.AppendLine();
        foreach (var register in model.Registers)
            sb.AppendLine($"    public {(register.Bits == 8 ? "byte" : "ushort")} {register.Name};");

        string nameList = string.Join(", ", model.Registers.Select(r => $"\"{r.Name}\""));
        sb.AppendLine();
        sb.AppendLine($"    private static readonly string[] s_registerNames = [{nameList}];");
        sb.AppendLine("    public System.Collections.Generic.IReadOnlyList<string> RegisterNames => s_registerNames;");

        sb.AppendLine();
        sb.AppendLine("    public ulong GetRegister(string name) => name switch");
        sb.AppendLine("    {");
        foreach (var register in model.Registers)
            sb.AppendLine($"        \"{register.Name}\" => {register.Name},");
        sb.AppendLine("        _ => throw new System.ArgumentException($\"Unknown register '{name}'.\", nameof(name)),");
        sb.AppendLine("    };");

        sb.AppendLine();
        sb.AppendLine("    public void SetRegister(string name, ulong value)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (name)");
        sb.AppendLine("        {");
        foreach (var register in model.Registers)
        {
            string cast = register.Bits == 8 ? "byte" : "ushort";
            sb.AppendLine($"            case \"{register.Name}\": {register.Name} = unchecked(({cast})value); break;");
        }
        sb.AppendLine("            default: throw new System.ArgumentException($\"Unknown register '{name}'.\", nameof(name));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        EmitExecution(sb, model);
    }

    private static void EmitExecution(StringBuilder sb, SpecModel model)
    {
        var pcRegister = model.Registers.First(r => r.Role == "ProgramCounter");
        string pc = pcRegister.Name;
        string pcType = pcRegister.Bits == 8 ? "byte" : "ushort";

        sb.AppendLine();
        sb.AppendLine("    // Instruction table parsed from the spec (execution emitted in chunk 2b):");
        foreach (var instruction in model.Instructions)
            sb.AppendLine($"    //   0x{instruction.Opcode:X2} {instruction.Mnemonic} {instruction.Mode}");

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Execute one instruction. Always advances CycleCount by at least one.</summary>");
        sb.AppendLine("    public void Step()");
        sb.AppendLine("    {");
        sb.AppendLine($"        byte opcode = ReadBus({pc});");
        sb.AppendLine($"        {pc} = unchecked(({pcType})({pc} + 1));");
        sb.AppendLine("        Execute(opcode);");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    public void Run(ref long cycleBudget)");
        sb.AppendLine("    {");
        sb.AppendLine("        while (cycleBudget > 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            long before = _cycles;");
        sb.AppendLine("            Step();");
        sb.AppendLine("            cycleBudget -= _cycles - before;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    private void Execute(byte opcode)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (opcode)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Per-opcode execution methods are emitted in chunk 2b.");
        sb.AppendLine("            default:");
        sb.AppendLine("                HandleUndefinedOpcode(opcode);");
        sb.AppendLine("                break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
