using System.Text;

namespace CpuEmulator.Generators;

internal static class CpuEmitter
{
    public static string Emit(SpecModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CpuEmulator.Generators from the CPU specification.");
        sb.AppendLine("// The hand-written partial MUST provide: a constructor, Reset(),");
        sb.AppendLine("// SetIrqLine(bool), SetNmiLine(bool), byte ReadBus(uint address)");
        sb.AppendLine("// (which increments _cycles), and HandleUndefinedOpcode(byte opcode).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed partial class {model.CpuName} : CpuEmulator.Core.ICpuCore");
        sb.AppendLine("{");
        sb.AppendLine($"    public string Architecture => \"{model.Architecture}\";");
        sb.AppendLine();
        sb.AppendLine("    internal long _cycles;");
        sb.AppendLine("    public long CycleCount => _cycles;");
        EmitBody(sb, model);   // Tasks 4-5 grow this
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBody(StringBuilder sb, SpecModel model)
    {
        // Grown in Tasks 4 (registers/introspection) and 5 (Step/Run/Execute).
    }
}
